name: ${name}
version: ${version}
main: ${groupId}.${artifactId}
api-version: 1.13
authors: [ Ashlyn ]
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
commands:
  casinoanimations:
    aliases: [ anima, casinoanimations ]
    permission-message: "You do not have permission to use this command noob"
    permission: casinoanimations.command
permissions:
  casinoanimations.admin:
    default: op
    children:
      - casinoanimations.command
  casinoanimations.command:
    default: op
    children:
      - casinoanimations.animation
      - casinoanimations.create
      - casinoanimations.delete
      - casinoanimations.reload
  casinoanimations.animation:
    default: op
    children:
      - casinoanimations.addframe
      - casinoanimations.editframe
      - casinoanimations.convert
      - casinoanimations.frameselection
      - casinoanimations.getframe
      - casinoanimations.gotoframe
      - casinoanimations.play
      - casinoanimations.stop
      - casinoanimations.settings
      - casinoanimations.rename
      - casinoanimations.removeframe
      - casinoanimations.copyframe
  casinoanimations.settings:
    default: op
    children:
      - casinoanimations.setworld
      - casinoanimations.togglereverse
      - casinoanimations.setload
      - casinoanimations.togglerandom
      - casinoanimations.setdelay
  casinoanimations.addframe:
    default: op
  casinoanimations.editframe:
    default: op
  casinoanimations.convert:
    default: op
  casinoanimations.delete:
    default: op
  casinoanimations.create:
    default: op
  casinoanimations.frameselection:
    default: op
  casinoanimations.getframe:
    default: op
  casinoanimations.gotoframe:
    default: op
  casinoanimations.play:
    default: op
  casinoanimations.reload:
    default: op
  casinoanimations.stop:
    default: op
  casinoanimations.setworld:
    default: op
  casinoanimations.togglereverse:
    default: op
  casinoanimations.setload:
    default: op
  casinoanimations.togglerandom:
    default: op
  casinoanimations.setdelay:
    default: op
  casinoanimations.rename:
    default: op
  casinoanimations.removeframe:
    default: op
  casinoanimations.copyframe:
    default: op