name: Create Release

on:
  push:
    branches:
      - 'main'  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Java 8, as required)
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Build the JAR, skip tests for faster builds

      - name: Publish JAR as Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Build-${{ github.run_number }}  # Generate tag name based on the run number
          name: Download  # Specify the release name
          draft: false
          prerelease: false
          files: target/CasinoAnimations-1.0.4.jar
          body: |
            Build Number: ${{ github.run_number }}

            For any questions or issues, feel free to open an issue.

            Happy animating!