name: Create Maven Release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[release-skip]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"

      - name: Build Maven package
        run: mvn clean install -DskipTests=true

      - name: Publish Maven package to GitHub Packages
        run: mvn deploy -DskipTests=true -Dusername=${{ secrets.MAVEN_USERNAME }} -Dpassword=${{ secrets.MAVEN_PASSWORD }}

      - name: Publish Release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          draft: false
          prerelease: false
          body: |
            Build Number: ${{ github.run_number }}
            
            This release contains the Maven package

            Release Highlights:
            - Testing some GitHub features.

            For any questions or issues, feel free to open an issue

            Happy animating!