name: Deploy to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build and deploy with Maven
        run: mvn deploy -DskipTests=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/AshlynDev/Casino-Animations -Dusername=${{ secrets.GITHUB_ACTOR }} -Dpassword=${{ secrets.GITHUB_TOKEN }}

      - name: Verify package deployment
        run: echo "Package deployment completed"