name: Create Release

on:
  push:
    branches:
      - 'main'  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Java 8, as required)
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          java-version: '8'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests  # Build the JAR, skip tests for faster builds

      # Step 4: Create GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/CasinoAnimations-1.0.4.jar  # Adjust this path to your JAR file location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub Token for authentication